package com.harmonygates.home

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.safeDrawingPadding
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.booleanResource
import androidx.compose.ui.res.integerResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.platform.LocalResources
import androidx.compose.ui.tooling.preview.Preview
import com.harmonygates.core.designsystem.artwork.ArtworkScreen
import com.harmonygates.core.designsystem.component.FeedbackTone
import com.harmonygates.core.designsystem.component.HarmonyPanel
import com.harmonygates.core.designsystem.component.HarmonyStatusChip
import com.harmonygates.core.designsystem.theme.HarmonyTheme
import com.harmonygates.R

/**
 * The home screen.
 *
 * Two presentations of the same contract. When the approved artwork from `interface/` is
 * present, the screen *is* the artwork with invisible controls over its named regions. Until
 * then it lists the same actions plainly.
 *
 * The fallback is not a guess at the approved design. 16_AGENT_EXECUTION_PROTOCOL.md §8 is
 * explicit that prose must not be approximated once a Figma source of truth exists, so this
 * makes no attempt to look like the real home screen — it just works, and says what it is
 * waiting for. Swapping in the artwork changes no behaviour, only how it is drawn.
 */
@Composable
fun HomeScreen(
    onAction: (HomeAction) -> Unit,
    modifier: Modifier = Modifier,
) {
    // All four generated by syncInterfaceArtwork from whatever is in interface/.
    val artworkPresent = booleanResource(R.bool.home_approved_available)
    val nativeWidth = integerResource(R.integer.home_approved_native_width)
    val nativeHeight = integerResource(R.integer.home_approved_native_height)
    val resources = LocalResources.current

    // The map is a few kilobytes and parses once per composition scope, not per frame.
    val spec = remember(resources, artworkPresent, nativeWidth, nativeHeight) {
        val source = resources.openRawResource(R.raw.home_interaction_map)
            .bufferedReader()
            .use { it.readText() }
        InteractionMapReader.read(
            source = source,
            fallbackWidth = HomeArtwork.DECLARED_WIDTH,
            fallbackHeight = HomeArtwork.DECLARED_HEIGHT,
        ).spec
    }

    // Both halves are needed. Artwork with no regions is a screen of dead pixels; regions with
    // no artwork is invisible buttons over nothing.
    if (artworkPresent && spec.regions.isNotEmpty()) {
        ArtworkScreen(
            artwork = painterResource(R.drawable.home_approved),
            spec = spec,
            onRegionClick = { regionId -> HomeAction.forRegion(regionId)?.let(onAction) },
            modifier = modifier,
            contentDescription = "Harmony Gates home",
            // The letterbox around a fitted 3:2 frame is part of the screen, so it is the app's
            // own ground rather than black.
            background = HarmonyTheme.colors.backgroundBase,
        )
    } else {
        HomeActionList(onAction = onAction, artworkPresent = artworkPresent, modifier = modifier)
    }
}

@Composable
private fun HomeActionList(
    onAction: (HomeAction) -> Unit,
    artworkPresent: Boolean,
    modifier: Modifier = Modifier,
) {
    Column(
        modifier = modifier
            .fillMaxSize()
            .safeDrawingPadding()
            .padding(HarmonyTheme.spacing.large),
        verticalArrangement = Arrangement.spacedBy(HarmonyTheme.spacing.medium),
    ) {
        Text(
            text = "Harmony Gates",
            color = HarmonyTheme.colors.onSurface,
            fontSize = HarmonyTheme.typography.heading,
        )

        HarmonyPanel(modifier = Modifier.fillMaxWidth()) {
            Column(verticalArrangement = Arrangement.spacedBy(HarmonyTheme.spacing.small)) {
                HarmonyStatusChip(
                    label = if (artworkPresent) "Artwork loaded, regions pending" else "Approved artwork pending",
                    tone = FeedbackTone.NEUTRAL,
                )
                Text(
                    text = if (artworkPresent) {
                        "The approved artwork is in the build. Fill in HomeArtwork.regionBounds " +
                            "with where each control sits and this screen becomes the artwork."
                    } else {
                        "Every control below is already wired to its Figma hit region. Commit the " +
                            "approved export to interface/ and rebuild; the artwork is picked up " +
                            "automatically."
                    },
                    color = HarmonyTheme.colors.onSurfaceMuted,
                    fontSize = HarmonyTheme.typography.caption,
                )
            }
        }

        LazyVerticalGrid(
            columns = GridCells.Adaptive(minSize = MINIMUM_TILE_WIDTH_DP),
            verticalArrangement = Arrangement.spacedBy(HarmonyTheme.spacing.small),
            horizontalArrangement = Arrangement.spacedBy(HarmonyTheme.spacing.small),
        ) {
            items(HomeAction.entries.toList(), key = { it.name }) { action ->
                if (action.destination.isImplemented) {
                    Button(onClick = { onAction(action) }, modifier = Modifier.fillMaxWidth()) {
                        Text(action.label)
                    }
                } else {
                    OutlinedButton(onClick = { onAction(action) }, modifier = Modifier.fillMaxWidth()) {
                        Text("${action.label} · phase ${action.destination.arrivesInPhase}")
                    }
                }
            }
        }
    }
}

private val MINIMUM_TILE_WIDTH_DP = androidx.compose.ui.unit.Dp(220f)

@Preview(showBackground = true, widthDp = 1024, heightDp = 700)
@Composable
private fun HomeScreenPreview() {
    HarmonyTheme {
        HomeScreen(onAction = {})
    }
}
