package com.harmonygates.core.music.voicing

import com.harmonygates.core.music.pitch.MidiNote

/**
 * Pure voicing transformations (04_HARMONY_DOMAIN_ENGINE.md §9).
 *
 * Every function returns a new voicing or null; nothing mutates. Null means "this shape does
 * not exist for this input" — too few voices to drop, or the result would leave the MIDI
 * range — and is always a legitimate answer rather than an error.
 *
 * Region 8 of the curriculum requires these to be generated by transformation rather than
 * looked up, so a drop-2 of an unusual chord behaves the same as a drop-2 of a familiar one.
 */
public object VoicingTransforms {

    /** Moves the lowest voice up an octave, [times] over. The classic inversion operation. */
    public fun invert(voicing: Voicing, times: Int = 1): Voicing? {
        require(times >= 0) { "Inversion count must be non-negative: $times" }
        var current = voicing
        repeat(times) {
            val tones = current.tones.toMutableList()
            val lowest = tones.removeAt(0)
            tones += lowest.copy(pitch = lowest.pitch + 1)
            if (tones.any { it.pitch.midiNoteOrNull == null }) return null
            current = voicingOf(current.chord, tones, family = null)
        }
        return current
    }

    /** Moves one voice by whole octaves, counted from the bass upwards. */
    public fun octaveDisplace(voicing: Voicing, voiceIndex: Int, octaves: Int): Voicing? {
        if (voiceIndex !in voicing.pitches.indices) return null
        val tones = voicing.tones.toMutableList()
        val moved = tones[voiceIndex]
        tones[voiceIndex] = moved.copy(pitch = moved.pitch + octaves)
        if (tones.any { it.pitch.midiNoteOrNull == null }) return null
        return voicingOf(voicing.chord, tones, family = VoicingFamily.OPEN)
    }

    /** Drops the second voice from the top an octave. Needs at least four voices. */
    public fun drop2(voicing: Voicing): Voicing? = drop(voicing, setOf(2), VoicingFamily.DROP_2, minimumVoices = 4)

    /** Drops the third voice from the top an octave. Needs at least four voices. */
    public fun drop3(voicing: Voicing): Voicing? = drop(voicing, setOf(3), VoicingFamily.DROP_3, minimumVoices = 4)

    /** Drops the second and fourth voices from the top an octave. Needs at least four voices. */
    public fun drop2And4(voicing: Voicing): Voicing? =
        drop(voicing, setOf(2, 4), VoicingFamily.DROP_2_AND_4, minimumVoices = 4)

    /**
     * Opens the voicing by moving the bass down an octave.
     *
     * This is the left-hand-root spread that Region 8 introduces: the same upper structure,
     * with air underneath it.
     */
    public fun spread(voicing: Voicing): Voicing? {
        if (voicing.voiceCount < 3) return null
        val tones = voicing.tones.toMutableList()
        val bass = tones[0]
        tones[0] = bass.copy(pitch = bass.pitch - 1)
        if (tones.any { it.pitch.midiNoteOrNull == null }) return null
        return voicingOf(voicing.chord, tones, family = VoicingFamily.SPREAD)
    }

    /**
     * Rebuilds the voicing in close position: same tones, each at the lowest octave that keeps
     * the stack ascending above the existing bass.
     */
    public fun close(voicing: Voicing): Voicing? {
        val ascending = voicing.tones.sortedBy { it.pitch.midiNote.value }
        val bass = ascending.first()
        val bassPitchClass = bass.pitch.midiNote.value.mod(12)
        // Order the upper tones by their distance above the bass rather than by their current
        // pitch. A dropped voice sits below tones it belongs above, so sorting by pitch alone
        // would rebuild the same wide shape instead of closing it.
        val tones = ascending.drop(1)
            .sortedBy { (it.pitch.midiNote.value - bassPitchClass).mod(12) }
        var previous = bass.pitch.midiNote.value
        val rebuilt = mutableListOf(bass)
        for (tone in tones) {
            val target = tone.pitch.midiNote.value.mod(12)
            var candidate = previous + 1
            while (candidate.mod(12) != target) candidate++
            val octaveShift = (candidate - tone.pitch.midiNote.value).floorDiv(12)
            val moved = tone.copy(pitch = tone.pitch + octaveShift)
            if (moved.pitch.midiNoteOrNull == null) return null
            rebuilt += moved
            previous = moved.pitch.midiNote.value
        }
        return voicingOf(voicing.chord, rebuilt, family = VoicingFamily.CLOSE)
    }

    /** Shifts the whole voicing by [octaves], preserving its shape and spelling. */
    public fun shiftOctaves(voicing: Voicing, octaves: Int): Voicing? {
        if (octaves == 0) return voicing
        val tones = voicing.tones.map { it.copy(pitch = it.pitch + octaves) }
        if (tones.any { it.pitch.midiNoteOrNull == null }) return null
        return voicingOf(voicing.chord, tones, family = voicing.metadata.family)
    }

    /**
     * Slides the voicing by whole octaves until it fits [range].
     *
     * Returns null when the voicing is simply wider than the range, rather than mangling the
     * shape to force a fit — a policy that cannot be satisfied should say so.
     */
    public fun constrainToRange(voicing: Voicing, range: IntRange): Voicing? {
        if (voicing.metadata.spanSemitones > range.last - range.first) return null
        for (octaves in OCTAVE_SEARCH) {
            val shifted = shiftOctaves(voicing, octaves) ?: continue
            if (shifted.pitches.all { it.value in range }) return shifted
        }
        return null
    }

    /** Shifts by octaves so the bass lands on [note], preserving relative spacing. */
    public fun withBassAt(voicing: Voicing, note: MidiNote): Voicing? {
        val difference = note.value - voicing.bass.value
        if (difference.mod(12) != 0) return null
        return shiftOctaves(voicing, difference / 12)
    }

    /** Shifts by octaves so the top lands on [note], preserving relative spacing. */
    public fun withTopAt(voicing: Voicing, note: MidiNote): Voicing? {
        val difference = note.value - voicing.top.value
        if (difference.mod(12) != 0) return null
        return shiftOctaves(voicing, difference / 12)
    }

    private fun drop(
        voicing: Voicing,
        positionsFromTop: Set<Int>,
        family: VoicingFamily,
        minimumVoices: Int,
    ): Voicing? {
        if (voicing.voiceCount < minimumVoices) return null
        if (positionsFromTop.any { it > voicing.voiceCount }) return null
        val tones = voicing.tones.toMutableList()
        for (position in positionsFromTop) {
            val index = tones.size - position
            val tone = tones[index]
            tones[index] = tone.copy(pitch = tone.pitch - 1)
        }
        if (tones.any { it.pitch.midiNoteOrNull == null }) return null
        return voicingOf(voicing.chord, tones, family = family)
    }

    /** Nearest octave first, so a voicing that already fits is returned unchanged. */
    private val OCTAVE_SEARCH = listOf(0, 1, -1, 2, -2, 3, -3, 4, -4)
}
